# Generated by Django 2.2.7 on 2019-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='exam_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_time',
            field=models.IntegerField(default=0, help_text='Enter in minutes'),
        ),
    ]
