# Generated by Django 2.2.7 on 2020-01-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20191201_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='start_date_time',
        ),
    ]
