# Generated by Django 2.2.7 on 2020-01-11 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_exam_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
