# Generated by Django 2.2.7 on 2020-01-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_question_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
