# Generated by Django 2.2.7 on 2020-01-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200110_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
